#!/usr/bin/env python
##
# Copyright (C) 2013 Jessica T. (Tsyesika) <xray7224@googlemail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
##

import json
import sys
import os
import logging
import optparse
import six

import requests
from pypump import PyPump, Client

try:
    from IPython import embed
    from IPython.config.loader import Config
except ImportError:
    six.print_("You need to have ipython installed to run this")
    sys.exit(1)

welcome_banner = """Welcome to the PyPump Shell,
We have setup some useful objects for you:

{table}

If you need help please visit our docs:
https://pypump.readthedocs.org/en/latest
"""

def ascii_table(headings, data):
    """ Draws an ascii table """
    # first we need to work out how long each column should be
    columns = {}
    for heading in headings:
        columns[heading] = len(heading)+1 # plus one for the extra padding

    # data could also overspill
    for record in data:
        for heading, d in record.items():
            dlen = len(d)+1
            if dlen > columns[heading]:
                columns[heading] = dlen


    table = {}
    # okay now we need to pad the headers readying for drawing
    for column, width in columns.items():
        table[column] = "{name}{padding}".format(
                name=column, padding=" "*(width-len(column))
                )

    heading = "| "
    for column in table.values():
        heading += column
        heading += "| "

    # now for the data
    table = {}
    for i, record in enumerate(data):
        table[i] = "| "
        for column, cdata in record.items():
            table[i] += "{data}{padding} | ".format(
                    data=cdata, padding=" "*(columns[column]-len(cdata)-1)
                    )

    # make the helper function which will draw the seporators
    def draw_sep(columns):
        """ Draws +----+--- etc... """
        sep = "+"
        for width in columns:
            sep += "-"*(width+1)
            sep += "+"

        return sep + "\r\n"

    sepper = lambda :draw_sep(columns.values())
    stable = sepper()
    stable += heading + "\r\n"
    stable += sepper()
    for value in table.values():
        stable += value + "\r\n"

    stable += sepper()
    return stable # few, glad that's over

def verifier(url):
    """ Asks for verification code for OAuth OOB """
    six.print_("Please open and follow the instructions:")
    six.print_(url)
    return six.moves.input("Verifier: ").lstrip(" ").rstrip(" ")

if __name__ == "__main__":
    parser = optparse.OptionParser()

    parser.add_option("-c", "--clean",
                      dest="clean",
                      action="store_true",
                      default=False,
                      help="Removes all stored OAuth credentials")

    parser.add_option("-l", "--list",
                      dest="list",
                      action="store_true",
                      default=False,
                      help="Lists all stored OAuth credentials")

    parser.add_option("-r", "--remove",
                      dest="remove",
                      help="Remove stored OAuth credentials for selected webfinger")

    parser.add_option("--log", "--loglevel",
                      dest="loglevel",
                      default="warning",
                      help="Set level of logging")

    parser.add_option("--logfile",
                      dest="logfile",
                      action="store_true",
                      default=False,
                      help="Write logging to pypump-shell.log")

    parser.add_option("--no-check-certificate",
                      dest="verify",
                      help="Accepts invalid SSL certificates")

    (options, args) = parser.parse_args()

    log_level = getattr(logging, options.loglevel.upper(), None)
    if not isinstance(log_level, int):
        raise ValueError('Invalid log level: %s' % options.loglevel)

    logfile = "pypump-shell.log" if options.logfile else None
    logging.basicConfig(level=log_level, filename=logfile)

    if options.clean:
        if os.path.isfile(store_path):
            os.remove(store_path)
            six.print_("Successfully removed all OAuth credentials")
        else:
            six.print_("No OAuth crendetials found.")
            sys.exit(1)

        sys.exit()

    webfinger = "" if len(args) <= 0 else args[0]

    if not webfinger:
        six.print_("You must specify a webfinger.")
        sys.exit(1)

    client = Client(
        webfinger=webfinger,
        name="PyPump Shell",
        type="native"
    )

    sys.stdout.write("-> Setting up PyPump  ")
    sys.stdout.flush() # actually get it on the screen - most terms wait for \n


    try:
        pump = PyPump(client=client, verifier_callback=verifier)
    except requests.exceptions.SSLError:
        # This is caused when there has been an invalid certificate.
        # We should ask the user if they want to continue (common to use
        # self-signed/invalid certificates in dev enviroment).
        six.print_("Couldn't validate SSL/TLS certificate for {0}".format(webfinger.split("@", 1)[1]))
        answer = None
        while answer not in ["y", "n"]:
            if answer is not None:
                six.print_("Sorry, please type 'y' or 'n' (Ctrl-C to exit).")

            answer = raw_input("Would you like to accept the invalid/untrusted certificate (y/n): ").lower()
            answer = answer.replace(" ", "")

        if answer == "n":
            sys.exit(0)

        # Create the same PyPump object as above but without ssl verification
        pump = PyPump(client=client, verifier_callback=verifier, verify=False)

    # bring curser back so banner walks over the setup message
    sys.stdout.write("\r")

    # drop them into a shell
    cfg = Config()
    cfg.InteractiveShell.confirm_exit = False

    # prep the welcome banner
    welcome_banner = welcome_banner.format(
        table=ascii_table(
            ["Variable", "Representation", "Type"],
            [
                {
                    "Variable": "pump",
                    "Representation": str(repr(pump)),
                    "Type": type(pump).__name__,
                },
            ]
        )
    )


    embed(
        config=cfg,
        banner1=welcome_banner,
        exit_msg="Remeber! Report any bugs to https://github.com/xray7224/PyPump/issues"
    )
